[package]
name = "aws-athena-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
aws-sdk-athena = "1.19.0"
tokio = { version = "1", features = ["full"] }
from-athena-derive = { path = "../from-athena-derive" }
anyhow = "1.0.82"
